# BUILD STAGE
FROM node:20-alpine AS builder

WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./
RUN npm run build

# RUNTIME STAGE (Sadece static service / nginx build context)
FROM nginx:alpine

# Nginx varsayılan ayarlarını kopyala
COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
